apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Puerto en el que será accesible el servicio
      targetPort: 5000  # Puerto en el contenedor
  type: ClusterIP