replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  storageClass: gp2
  accessModes:
    - ReadWriteOnce
  size: 1Gi

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
